### ISSUE TITLE
Remind me during the workshop to take pics!

### ISSUE THREAD

**Issue by EMTuckerLab** [globalbioticinteractions/ecm-workshop#5]
If you can help remind me during the workshop next week to take some photos of people working on the activities, that would be awesome. I usually have me phone on me, but tend to get caught up in things and forget to take photos of activities. It would be nice to have some photos for future use :)
Thanks!!!

**Comment by jhpoelen** [comment]
@EMTuckerLabUMMZ did you take any pictures during the workshop? I forgot to remind you during the workshop as I was devoting all my energy to facilitate our virtual friends.

**Comment by EMTuckerLab** [comment]
Thanks Jorrit! I did take a handful of photos - just emailed you a link (it has editing properties, so not adding it here...). 
😃

**Comment by jhpoelen** [comment]
Thanks for taking the workshop pictures. Are the participants ok with using the pictures in blog post etc. ? Also, I was wondering whether we can ask some of  the participants to write a blog post about their experience.

**Comment by EMTuckerLab** [comment]
I didn't specifically ask if folks were ok with posting their photos - we could send a group email, or ask Floyd to send one (perhaps pertaining to all shared images since folks were already ask to share their photos too). 
As for a blog post, I'm guessing it may be more than most participants want to put in time wise, but it doesn't hurt to ask. Worst that could happen is nobody volunteers. Would this be for the GloBI blog, or somewhere else?

**Comment by jhpoelen** [comment]
I'd be happy to put it on https://globalbioticinteractions.org/blog (you can add one yourself at https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/tree/main/_posts e.g., https://github.com/globalbioticinteractions/globalbioticinteractions.github.io/blob/main/_posts/2022-03-16-Iguana.md). 

And, I am open to using any other publication platform that help share the excitement and outcomes of the ECM workshop. Perhaps you and/or Floyd have some ideas on this. Also, I'd suggest to consider a press-release like cross-posting idea, so that ASU, SI, and other institutions can easily copy-paste the blurb onto their institutional new feeds.
